{
 "title": "Weather Cache Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prom", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cache lock duration avg time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(cache_lock_wait_seconds_sum[5m]) / clamp_min(rate(cache_lock_wait_seconds_count[5m]), 1)",
     "legendFormat": "Avg lock time"
    }
   ]
  },
  {
   "title": "Cache lock wait total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(cache_lock_wait_seconds_count[1m])",
     "legendFormat": "Lock time total"
    }
   ]
  },
  {
   "title": "HTTP request avg time",
   "type": "timeseries",
   "description": "Average time for HTTP request to be processed. Excludes /health ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(method, route) (rate(http_requests_duration_seconds_sum{instance=\"host.docker.internal:8080\"}[5m]))\n/\nsum by(method, route) (rate(http_requests_duration_seconds_count{instance=\"host.docker.internal:8080\"}[5m]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "500 error rate, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 * (\n  sum(rate(http_requests_duration_seconds_count{status=~\"5..\"}[5m]))\n  /\n  sum(rate(http_requests_duration_seconds_count[5m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "barchart",
   "description": "Cache hits, miss, locks total",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(cache_total{result=\"hit\"}[1m])",
     "legendFormat": "Cache hit total"
    },
    {
     "expr": "increase(cache_total{result=\"miss\"}[1m])",
     "legendFormat": "Cache miss total"
    },
    {
     "expr": "increase(cache_lock_wait_total{instance=\"host.docker.internal:8080\"}[1m])",
     "legendFormat": "Cache locks total"
    }
   ]
  }
 ]
}