apiVersion: 1
groups:
    - orgId: 1
      name: HTTP evaluation group
      folder: httpInternalErrorRate
      interval: 1m
      rules:
        - uid: feu0divdi3tvkb
          title: 500 error rate, %
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: prometheus
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: prometheus
                editorMode: code
                expr: |-
                    100 * (
                      sum(rate(http_requests_duration_seconds_count{status=~"5.."}[5m]))
                      /
                      sum(rate(http_requests_duration_seconds_count[5m]))
                    )
                instant: true
                interval: ""
                intervalMs: 5000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 5
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: 1abfd8c9-3191-4f9d-a49d-feb37aa2ff16
          panelId: 10
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: 1abfd8c9-3191-4f9d-a49d-feb37aa2ff16
            __panelId__: "10"
            description: Internal server error (500) rate exceeds 5%
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
