name: Lint

on:
    pull_request:
        branches:
            - main
permissions:
    contents: read
    pull-requests: read
jobs:
    run-linters:
        name: Linter
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-go@v5
            with:
              go-version: '1.24.1'
          - name: golangci-lint
            uses: golangci/golangci-lint-action@v8
            with:
                version: v2.1
                only-new-issues: true
